### ISSUE TITLE
Curious to know why istanbul instead of nyc?

### ISSUE THREAD

**Issue by sarbbottam** [tbranyen/hyperlist#3]
❓ 
With respect to 387e99b72a7fc0304beb54c9b10e77e1acdfd6d2, I am curious to know why `istanbul` instead of `nyc`?

Thanks!

**Comment by tbranyen** [comment]
nyc was producing bad coverage since it uses an old version of istanbul. so instead of fighting with something that was never designed for ES2015, I opt'd for the latest unstable of istanbul that is designed for ES2015 syntax. This produces significantly more accurate reports that are useful for isolating dead/code refactor points.

**Comment by sarbbottam** [comment]
Ahh, thanks!

I did not experience such with `nyc` or may be I overlooked. I tried `istanbul-alpha` sometimes back (last week of April'16), it did not create `coverage`, even the `dir`, did not dig into it. 😄 Moved back to `nyc`.
